version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - './storage:/app/storage'

  db:
    image: mongo:4.4
    container_name: db
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    restart: always
    volumes:
      - "./db/init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro"
      - "./db/data/db-files:/data/db"
    ports:
      - 27017:27017